steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/ztraveler-repo/ztraveler-backend', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/ztraveler-repo/ztraveler-backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - run
      - deploy
      - ztraveler-backend
      - --image
      - us-central1-docker.pkg.dev/$PROJECT_ID/ztraveler-repo/ztraveler-backend
      - --platform
      - managed
      - --region
      - us-central1
      - --allow-unauthenticated
      - --set-env-vars
      - GOOGLE_API_KEY=your_gemini_key,MONGO_URI=your_mongodb_uri,REDIS_URL=your_redis_url
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/ztraveler-repo/ztraveler-backend
